name: 'hardenedBSD CI'
description: 'Run CI commands in a hardenedBSD virtual machine'
inputs:
  release:
    description: 'The VM release'
    required: false
    default: '16-CURRENT'
  arch:
    description: 'The VM CPU'
    required: false
    default: 'x86_64'
  filesystem:
    description: 'The VM filesystem'
    required: false
    default: 'ufs'
  run:
    description: 'The command(s) execute on the VM'
    required: false
    default: 'uname -a'
  mem:
    description: 'The amount of memory to allocate to the VM'
    required: false
    default: '6144'

branding:
  icon: 'activity'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Build VM
      shell: bash
      run: |
        cd ${{ github.action_path }}
        go run ./...

      env:
        INPUT_RUN: ${{ inputs.run }}
        INPUT_RELEASE: ${{ inputs.release }}
        INPUT_ARCH: ${{ inputs.arch }}
        INPUT_FILESYSTEM: ${{ inputs.filesystem }}
        INPUT_MEM: ${{ inputs.mem }}
